# Generated by Django 2.1.4 on 2019-01-11 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_emp', models.CharField(max_length=100)),
                ('age_emp', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)])),
                ('email_emp', models.CharField(default='enter username', max_length=256, null=True, unique=True, validators=[django.core.validators.EmailValidator])),
                ('password_emp', models.CharField(default='enter password', max_length=6)),
                ('mob_emp', models.CharField(blank=True, max_length=10, null=True)),
                ('address_emp', models.CharField(max_length=100)),
            ],
        ),
    ]
