# Generated by Django 2.1.4 on 2018-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
