# Generated by Django 2.1.4 on 2018-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181220_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('S', 'SAVINGS_ACCOUNT'), ('C', 'CURRENT_ACCOUNT'), ('F', 'FIXED_DEPOSITE'), ('R', 'RECURRING_DEPOSITE')], max_length=1),
        ),
    ]
