# Generated by Django 2.1.4 on 2018-12-22 14:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181221_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(500)])),
                ('credit', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(500)])),
                ('debit', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(500)]))])),
                ('description', models.CharField(default='BALANCE', max_length=100)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
