# Generated by Django 2.1.4 on 2018-12-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181223_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='credits',
            new_name='credit',
        ),
    ]
