# Generated by Django 2.1.4 on 2018-12-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181226_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='receiver',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_to',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='main.User'),
        ),
    ]
