# Generated by Django 2.1.4 on 2018-12-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181226_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.CharField(default='Money transfer', max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='main.User'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.User'),
        ),
    ]
