# Generated by Django 2.1.4 on 2018-12-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181226_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='description',
        ),
    ]
