# Generated by Django 2.1.4 on 2018-12-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181226_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_to',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_money',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_money', to='main.User'),
        ),
    ]
