# Generated by Django 2.1.4 on 2018-12-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181226_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_money',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
